# follow Mathieu's paper
bw:
    format: "values"
    values:
        - 0.01
        - 0.1
        - 1
        - 10
        - 100
    dtype: "float"

K:
    format: "values"
    values:
        - 0.1
        - 1
        - 10
    dtype: "float"

p:
    format: "values"
    values:
        - 0.1
        - 1
        - 10
    dtype: "float"

